server:
    session:
      timeout: 600
    port: 8962

spring:
  aop:
    proxy-target-class: true
  application:
    name: kkcms-api
  session:
    store-type: redis
  redis:
      host: localhost
      database: 9
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 0
        max-wait: -1
      password: wh970121
  datasource:
        name: kkcms
        url: jdbc:mysql://127.0.0.1:3306/kkcms?useUnicode=true&characterEncoding=UTF8&useSSL=true
        username: root
        password: wh970121
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          initial-size: 1
          max-active: 20
          min-idle: 5
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          poolPreparedStatements: true
          max-pool-prepared-statement-per-connection-size: 100
          filters: stat,wall,slf4j
          web-stat-filter.enabled: true
          web-stat-filter.url-pattern: /*
          web-stat-filter.session-stat-enable: true
          web-stat-filter.session-stat-max-count: 1000
          web-stat-filter.profile-enable: true
          stat-view-servlet.enabled: true
          stat-view-servlet.url-pattern: /druid/*
          stat-view-servlet.reset-enable: true
          stat-view-servlet.login-username: kkdruid
          stat-view-servlet.login-password: wh970121
          filter.stat.slow-sql-millis: 5000
          filter.stat.log-slow-sql: true
          aop-patterns: com.kk.api.service.*,com.kk.api.dao.*


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8961/eureka/



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kk.api.entity
  configuration:
    lazy-loading-enabled: true

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin123456


